# Header
menu:
  主页: /
  所有文章: /archives
  
# SubNav
subnav:
  github: "https://github.com/yueshengwujie/yueshengwujie.github.io"
  weibo: "#"
  rss: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "/photo/head.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

friends: false


aboutme: 作为一名程序猿，我内心仍拥有诗人般的优雅，也许我的人生，在转角处选错了方向，但我从未后悔！